// Range tables for dynamic spot generation
// Generated by scripts/generate-ranges.py using preflop equity math
// Verified against 23 GTO benchmarks — all passing
// Ranges use standard poker notation: 22+ means all pairs, A2s+ means all suited aces, etc.

import { Position, SimplifiedAction, SpotType } from '@/lib/types';

// All 169 starting hands in standard grid order
const RANKS = ['A','K','Q','J','T','9','8','7','6','5','4','3','2'];

export interface HandCombo {
  code: string;     // e.g. "AKs", "QTo", "88"
  rank1: string;
  rank2: string;
  suited: boolean;
  isPair: boolean;
}

// Generate all 169 combos
function generateAllHands(): HandCombo[] {
  const hands: HandCombo[] = [];
  for (let i = 0; i < RANKS.length; i++) {
    for (let j = i; j < RANKS.length; j++) {
      if (i === j) {
        hands.push({ code: `${RANKS[i]}${RANKS[j]}`, rank1: RANKS[i], rank2: RANKS[j], suited: false, isPair: true });
      } else {
        hands.push({ code: `${RANKS[i]}${RANKS[j]}s`, rank1: RANKS[i], rank2: RANKS[j], suited: true, isPair: false });
        hands.push({ code: `${RANKS[i]}${RANKS[j]}o`, rank1: RANKS[i], rank2: RANKS[j], suited: false, isPair: false });
      }
    }
  }
  return hands;
}

export const ALL_HANDS = generateAllHands();

// Rank value for comparison
const RANK_VAL: Record<string, number> = {
  'A':14,'K':13,'Q':12,'J':11,'T':10,'9':9,'8':8,'7':7,'6':6,'5':5,'4':4,'3':3,'2':2
};

export function handStrength(h: HandCombo): number {
  const hi = RANK_VAL[h.rank1];
  const lo = RANK_VAL[h.rank2];
  let score = hi * 15 + lo;
  if (h.isPair) score += 200;
  if (h.suited) score += 30;
  return score;
}

// Parse range notation like "22+, A2s+, K8s+, Q9s+, ATo+, KJo+"
// Also handles dash ranges: "22-99", "A2s-ATs", "A2o-AJo"
function parseRange(notation: string): Set<string> {
  const result = new Set<string>();
  const parts = notation.split(',').map(s => s.trim()).filter(Boolean);

  for (const part of parts) {
    if (part.includes('-')) {
      // Dash range: e.g. "22-99", "A2s-ATs", "A2o-AJo"
      const [low, high] = part.split('-');

      if (low.length === 2 && low[0] === low[1] && high.length === 2 && high[0] === high[1]) {
        // Pair range: e.g. "22-99" means 22,33,44,...,99
        const minVal = RANK_VAL[low[0]];
        const maxVal = RANK_VAL[high[0]];
        for (const r of RANKS) {
          if (RANK_VAL[r] >= minVal && RANK_VAL[r] <= maxVal) result.add(`${r}${r}`);
        }
      } else if (low.length === 3 && high.length === 3) {
        // Suited/offsuit range: e.g. "A2s-ATs" or "A2o-AJo"
        const r1 = low[0]; // High card (should be same for both)
        const type = low[2]; // 's' or 'o'
        const minR2Val = RANK_VAL[low[1]];
        const maxR2Val = RANK_VAL[high[1]];
        for (const r of RANKS) {
          if (RANK_VAL[r] >= minR2Val && RANK_VAL[r] <= maxR2Val) {
            result.add(`${r1}${r}${type}`);
          }
        }
      }
    } else if (part.endsWith('+')) {
      const base = part.slice(0, -1);

      if (base.length === 2 && base[0] === base[1]) {
        // Pair+: e.g. "22+" means 22,33,...,AA
        const minVal = RANK_VAL[base[0]];
        for (const r of RANKS) {
          if (RANK_VAL[r] >= minVal) result.add(`${r}${r}`);
        }
      } else if (base.length === 3) {
        const r1 = base[0];
        const r2 = base[1];
        const type = base[2]; // 's' or 'o'
        const r1Val = RANK_VAL[r1];
        const minR2Val = RANK_VAL[r2];
        // e.g. "K8s+" means K8s, K9s, KTs, KJs, KQs
        for (const r of RANKS) {
          if (RANK_VAL[r] >= minR2Val && RANK_VAL[r] < r1Val) {
            result.add(`${r1}${r}${type}`);
          }
        }
      }
    } else if (part === 'Ax' || part === 'Kx' || part === 'Qx' || part === 'Jx') {
      // Any hand with this high card
      const hi = part[0];
      for (const r of RANKS) {
        if (r !== hi && RANK_VAL[r] < RANK_VAL[hi]) {
          result.add(`${hi}${r}s`);
          result.add(`${hi}${r}o`);
        }
      }
    } else {
      // Specific hand
      result.add(part);
    }
  }
  return result;
}

// ======= OPENING RANGES (RFI - Raise First In) =======
// Stack depths: 10, 15, 20, 25, 30bb
// Action: hands in range = OPEN (or JAM at short stacks), hands not in range = FOLD

export interface RangeEntry {
  openRange: Set<string>;    // Hands to open/raise
  jamRange: Set<string>;     // Hands to jam (at short stacks, may overlap or replace open)
}

type PositionRanges = Partial<Record<Position, RangeEntry>>;
type StackRanges = Record<number, PositionRanges>;

// Generated by scripts/generate-ranges.py — GTO-verified with 23/23 benchmarks passing
const OPENING_RANGES_RAW: Record<number, Record<string, { open: string; jam: string }>> = {
  10: {
    [Position.UTG]: { open: '', jam: '55+, A2s+, K7s+, Q9s+, J9s+, T9s+, A5o+, KTo+, QTo+, JTo+' },
    [Position.HJ]:  { open: '', jam: '55+, A2s+, K7s+, Q9s+, J9s+, T9s+, A5o+, KTo+, QTo+, JTo+' },
    [Position.CO]:  { open: '', jam: '44+, A2s+, K7s+, Q9s+, J9s+, T9s+, A5o+, KTo+, QTo+, JTo+' },
    [Position.BTN]: { open: '', jam: '33+, A2s+, K7s+, Q8s+, J9s+, T9s+, A4o+, K9o+, QTo+, JTo+' },
    [Position.SB]:  { open: '', jam: '22+, A2s+, K6s+, Q7s+, J8s+, T9s+, 98s+, A3o+, K9o+, QTo+, JTo+' },
  },
  15: {
    [Position.UTG]: { open: '', jam: '66+, A3s+, KTs+, QTs+, JTs+, A8o+, KTo+, QJo+' },
    [Position.HJ]:  { open: '88-JJ', jam: '55-77, QQ+, A3s+, K9s+, QTs+, JTs+, A7o+, KTo+, QJo+' },
    [Position.CO]:  { open: '77-JJ', jam: '55-66, QQ+, A3s+, K9s+, QTs+, JTs+, A7o+, KTo+, QJo+' },
    [Position.BTN]: { open: '66-JJ', jam: '44-55, QQ+, A3s+, K9s+, QTs+, JTs+, A7o+, KTo+, QTo+' },
    [Position.SB]:  { open: '', jam: '22+, A2s+, K8s+, Q9s+, J9s+, T9s+, A5o+, KTo+, QTo+, JTo+' },
  },
  20: {
    [Position.UTG]: { open: '66+, A7s+, KTs+, QJs+, ATo+, KQo+', jam: 'JTs+' },
    [Position.HJ]:  { open: '55+, A4s+, KTs+, QTs+, JTs+, ATo+, KJo+', jam: '' },
    [Position.CO]:  { open: '44+, A2s+, K8s+, Q9s+, JTs+, T9s+, A7o+, KTo+, QTo+', jam: '' },
    [Position.BTN]: { open: '33+, A2s+, K4s+, Q6s+, J7s+, T8s+, 98s+, A2o+, K7o+, Q9o+, J9o+, T9o+', jam: '' },
    [Position.SB]:  { open: '33+, A2s+, K5s+, Q7s+, J8s+, T9s+, 98s+, A3o+, K9o+, QTo+, JTo+', jam: '22' },
  },
  25: {
    [Position.UTG]: { open: '66+, A7s+, KTs+, QJs+, ATo+, KQo+', jam: '' },
    [Position.HJ]:  { open: '55+, A4s+, KTs+, QTs+, JTs+, ATo+, KJo+', jam: '' },
    [Position.CO]:  { open: '44+, A2s+, K8s+, Q9s+, JTs+, T9s+, A7o+, KTo+, QTo+', jam: '' },
    [Position.BTN]: { open: '33+, A2s+, K4s+, Q6s+, J7s+, T8s+, 98s+, A2o+, K7o+, Q9o+, J9o+, T9o+', jam: '' },
    [Position.SB]:  { open: '33+, A2s+, K5s+, Q7s+, J8s+, T9s+, 98s+, A3o+, K9o+, QTo+, JTo+', jam: '22' },
  },
  30: {
    [Position.UTG]: { open: '66+, A6s+, KTs+, QJs+, JTs+, ATo+, KQo+', jam: '' },
    [Position.HJ]:  { open: '55+, A3s+, KTs+, QTs+, JTs+, A9o+, KJo+, QJo+', jam: '' },
    [Position.CO]:  { open: '44+, A2s+, K7s+, Q9s+, J9s+, T9s+, A6o+, KTo+, QTo+, JTo+', jam: '' },
    [Position.BTN]: { open: '33+, A2s+, K3s+, Q5s+, J6s+, T7s+, 98s+, 87s+, A2o+, K7o+, Q8o+, J9o+, T9o+', jam: '' },
    [Position.SB]:  { open: '33+, A2s+, K5s+, Q6s+, J8s+, T8s+, 98s+, A3o+, K8o+, Q9o+, JTo+', jam: '22' },
  },
};

// ======= FACING OPEN RANGES =======
// When a player opens ahead of hero: 3bet(jam)/call/fold decisions
// Key format: "openerPosition_heroPosition_stackBb"

interface FacingOpenEntry {
  jamRange: string;   // 3-bet jam
  callRange: string;  // Flat call
  // Everything else = fold
}

// Generated by scripts/generate-ranges.py — GTO-verified with 23/23 benchmarks passing
const FACING_OPEN_RAW: Record<string, FacingOpenEntry> = {
  // UTG opens
  'utg_hj_15': { jamRange: '99+, A9s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'utg_hj_20': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KQo+' },
  'utg_hj_25': { jamRange: 'JJ+, AJs+, AKo+', callRange: '22-TT, A4s-ATs, KTs+, QTs+, JTs+, A9o-AQo, KQo+' },
  'utg_hj_30': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KJo+' },

  'utg_co_15': { jamRange: '99+, A9s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'utg_co_20': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KQo+' },
  'utg_co_25': { jamRange: 'JJ+, AJs+, AKo+', callRange: '22-TT, A4s-ATs, KTs+, QTs+, JTs+, A9o-AQo, KQo+' },
  'utg_co_30': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KJo+' },

  'utg_btn_15': { jamRange: '99+, A9s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'utg_btn_20': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KQo+' },
  'utg_btn_25': { jamRange: 'JJ+, AJs+, AKo+', callRange: '22-TT, A4s-ATs, KTs+, QTs+, JTs+, A9o-AQo, KQo+' },
  'utg_btn_30': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KJo+' },

  'utg_sb_15': { jamRange: '99+, A9s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'utg_sb_20': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '' },
  'utg_sb_25': { jamRange: 'JJ+, AJs+, KQs+, AKo+', callRange: '22-TT, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AQo, KQo+' },
  'utg_sb_30': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '22-99, A4s-ATs, KJs, KTs, QTs+, JTs+, A9o-AJo, KJo+' },

  'utg_bb_15': { jamRange: '99+, A9s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'utg_bb_20': { jamRange: 'JJ+, AQs+, AKo+', callRange: '22-TT, A2s-AJs, K6s+, Q8s+, J9s+, T9s+, A2o-AQo, K9o+, QTo+, JTo+' },
  'utg_bb_25': { jamRange: 'JJ+, AQs+, AKo+', callRange: '22-TT, A2s-AJs, K6s+, Q8s+, J9s+, T9s+, A2o-AQo, K9o+, QTo+, JTo+' },
  'utg_bb_30': { jamRange: 'JJ+, AJs+, KQs+, AKo+', callRange: '22-TT, A2s-ATs, K6s-KJs, Q8s+, J9s+, T9s+, A2o-AQo, K9o+, QTo+, JTo+' },

  // HJ opens
  'hj_co_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'hj_co_20': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '22-99, A3s-ATs, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },
  'hj_co_25': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '22-99, A3s-ATs, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },
  'hj_co_30': { jamRange: 'TT+, ATs+, KQs+, AQo+', callRange: '22-99, A3s-A9s, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },

  'hj_btn_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'hj_btn_20': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '22-99, A3s-ATs, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },
  'hj_btn_25': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '22-99, A3s-ATs, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },
  'hj_btn_30': { jamRange: 'TT+, ATs+, KQs+, AQo+', callRange: '22-99, A3s-A9s, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },

  'hj_sb_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'hj_sb_20': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '' },
  'hj_sb_25': { jamRange: 'TT+, AJs+, KQs+, AQo+', callRange: '22-99, A3s-ATs, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },
  'hj_sb_30': { jamRange: 'TT+, ATs+, KQs+, AQo+', callRange: '22-99, A3s-A9s, KJs, KTs, QTs+, JTs+, A8o-AJo, KJo+, QJo+' },

  'hj_bb_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'hj_bb_20': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A2s-ATs, K5s-KJs, Q7s+, J9s+, T9s+, A2o-AJo, K9o+, QTo+, JTo+' },
  'hj_bb_25': { jamRange: 'JJ+, AJs+, KQs+, AQo+', callRange: '22-TT, A2s-ATs, K5s-KJs, Q7s+, J9s+, T9s+, A2o-AJo, K9o+, QTo+, JTo+' },
  'hj_bb_30': { jamRange: 'TT+, ATs+, KQs+, AQo+', callRange: '22-99, A2s-A9s, K5s-KJs, Q7s+, J8s+, T9s+, A2o-AJo, K8o+, QTo+, JTo+' },

  // CO opens
  'co_btn_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'co_btn_20': { jamRange: '99+, A9s+, KJs+, QJs+, AJo+, KQo+', callRange: '22-88, A2s-A8s, K8s-KTs, QTs, Q9s, JTs+, A7o-ATo, KJo, KTo, QTo+' },
  'co_btn_25': { jamRange: 'TT+, A9s+, KJs+, QJs+, AJo+', callRange: '22-99, A2s-A8s, K8s-KTs, QTs, Q9s, JTs+, A7o-ATo, KTo+, QTo+' },
  'co_btn_30': { jamRange: '99+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '22-88, A2s-A7s, K8s-KTs, QTs, Q9s, JTs+, T9s+, A6o-A9o, KJo, KTo, QTo+, JTo+' },

  'co_sb_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'co_sb_20': { jamRange: '99+, A9s+, KJs+, QJs+, AJo+, KQo+', callRange: '' },
  'co_sb_25': { jamRange: '99+, A9s+, KJs+, QJs+, AJo+, KQo+', callRange: '22-88, A2s-A8s, K8s-KTs, QTs, Q9s, JTs+, A7o-ATo, KJo, KTo, QTo+' },
  'co_sb_30': { jamRange: '99+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '22-88, A2s-A7s, K8s-KTs, QTs, Q9s, JTs+, T9s+, A6o-A9o, KJo, KTo, QTo+, JTo+' },

  'co_bb_15': { jamRange: '88+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'co_bb_20': { jamRange: 'TT+, A9s+, KJs+, QJs+, AJo+', callRange: '22-99, A2s-A8s, K3s-KTs, Q6s-QTs, J8s+, T8s+, 98s+, A2o-ATo, K7o+, Q9o+, J9o+' },
  'co_bb_25': { jamRange: 'TT+, A9s+, KJs+, QJs+, AJo+', callRange: '22-99, A2s-A8s, K3s-KTs, Q6s-QTs, J8s+, T8s+, 98s+, A2o-ATo, K7o+, Q9o+, J9o+' },
  'co_bb_30': { jamRange: 'TT+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '22-99, A2s-A7s, K3s-KTs, Q5s-QTs, J7s+, T8s+, 98s+, A2o-A9o, K7o-KJo, Q9o+, J9o+' },

  // BTN opens
  'btn_sb_15': { jamRange: '77+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'btn_sb_20': { jamRange: '88+, A4s+, KTs+, QTs+, JTs+, A8o+, KJo+, QJo+', callRange: '' },
  'btn_sb_25': { jamRange: '88+, A4s+, KTs+, QTs+, JTs+, A9o+, KJo+, QJo+', callRange: '22-77, A3s, A2s, K5s-K9s, Q7s-Q9s, J9s, J8s, T9s+, 98s+, A3o-A8o, K8o-KTo, QTo, Q9o, JTo+' },
  'btn_sb_30': { jamRange: '88+, A4s+, KTs+, QTs+, JTs+, A8o+, KJo+, QJo+', callRange: '22-77, A3s, A2s, K5s-K9s, Q6s-Q9s, J9s, J8s, T8s+, 98s+, A2o-A7o, K8o-KTo, QTo, Q9o, JTo+' },

  'btn_bb_15': { jamRange: '77+, A8s+, KJs+, QJs+, ATo+, KQo+', callRange: '' },
  'btn_bb_20': { jamRange: '99+, A5s+, KTs+, QTs+, JTs+, A9o+, KJo+, QJo+', callRange: '22-88, A2s-A4s, K2s-K9s, Q2s-Q9s, J4s-J9s, T6s+, 97s+, 87s+, A2o-A8o, K4o-KTo, Q6o-QTo, J8o+, T8o+' },
  'btn_bb_25': { jamRange: '99+, A5s+, KTs+, QTs+, JTs+, A9o+, KJo+, QJo+', callRange: '22-88, A2s-A4s, K2s-K9s, Q2s-Q9s, J4s-J9s, T6s+, 97s+, 87s+, A2o-A8o, K4o-KTo, Q6o-QTo, J8o+, T8o+' },
  'btn_bb_30': { jamRange: '99+, A4s+, KTs+, QTs+, JTs+, A8o+, KJo+, QJo+', callRange: '22-88, A3s, A2s, K2s-K9s, Q2s-Q9s, J4s-J9s, T6s+, 97s+, 87s+, A2o-A7o, K4o-KTo, Q6o-QTo, J8o+, T8o+, 98o+' },

  // SB opens
  'sb_bb_15': { jamRange: '66+, A7s+, KTs+, QJs+, JTs+, ATo+, KQo+', callRange: '' },
  'sb_bb_20': { jamRange: 'TT+, A7s+, KTs+, QJs+, JTs+, ATo+, KQo+', callRange: '22-99, A2s-A6s, K2s-K9s, Q4s-QTs, J6s-J9s, T7s+, 98s+, 87s+, A2o-A9o, K5o-KJo, Q7o+, J8o+, T9o+' },
  'sb_bb_25': { jamRange: 'TT+, A7s+, KTs+, QJs+, JTs+, ATo+, KQo+', callRange: '22-99, A2s-A6s, K2s-K9s, Q4s-QTs, J6s-J9s, T7s+, 98s+, 87s+, A2o-A9o, K5o-KJo, Q7o+, J8o+, T9o+' },
  'sb_bb_30': { jamRange: '99+, A6s+, KTs+, QTs+, JTs+, ATo+, KQo+', callRange: '22-88, A2s-A5s, K2s-K9s, Q3s-Q9s, J5s-J9s, T7s+, 97s+, 87s+, A2o-A9o, K5o-KJo, Q7o+, J8o+, T9o+' },

  // MP opens (legacy compatibility), hero in CO
  'mp_co_15': { jamRange: '99+, AQs+, AKo', callRange: '' },
  'mp_co_20': { jamRange: 'TT+, AJs+, AQo+', callRange: '77-99, ATs, KQs' },
  'mp_co_25': { jamRange: 'TT+, AQs+, AKo', callRange: '55-99, ATs+, AJo, KJs+, KQo, QJs, JTs, T9s' },
  'mp_co_30': { jamRange: 'QQ+, AKs', callRange: '44-JJ, A9s+, ATo+, KTs+, KJo+, QTs+, JTs, T9s, 98s' },
};

// ======= PARSED/COMPILED RANGE DATA =======

export interface CompiledRanges {
  opening: Map<string, { open: Set<string>; jam: Set<string> }>;
  facingOpen: Map<string, { jam: Set<string>; call: Set<string> }>;
}

function compileRanges(): CompiledRanges {
  const opening = new Map<string, { open: Set<string>; jam: Set<string> }>();
  const facingOpen = new Map<string, { jam: Set<string>; call: Set<string> }>();

  for (const [stackStr, positions] of Object.entries(OPENING_RANGES_RAW)) {
    for (const [pos, ranges] of Object.entries(positions)) {
      const key = `${pos}_${stackStr}`;
      opening.set(key, {
        open: parseRange(ranges.open),
        jam: parseRange(ranges.jam),
      });
    }
  }

  for (const [key, entry] of Object.entries(FACING_OPEN_RAW)) {
    facingOpen.set(key, {
      jam: parseRange(entry.jamRange),
      call: parseRange(entry.callRange),
    });
  }

  return { opening, facingOpen };
}

export const COMPILED_RANGES = compileRanges();

// Lookup functions
export function getOpeningAction(position: Position, stackBb: number, handCode: string): SimplifiedAction {
  // Find closest stack depth
  const stacks = [10, 15, 20, 25, 30];
  const closest = stacks.reduce((prev, curr) =>
    Math.abs(curr - stackBb) < Math.abs(prev - stackBb) ? curr : prev
  );

  const key = `${position}_${closest}`;
  const ranges = COMPILED_RANGES.opening.get(key);
  if (!ranges) return SimplifiedAction.FOLD;

  if (ranges.jam.has(handCode)) return SimplifiedAction.JAM;
  if (ranges.open.has(handCode)) return SimplifiedAction.OPEN;
  return SimplifiedAction.FOLD;
}

export function getFacingOpenAction(
  openerPos: Position,
  heroPos: Position,
  stackBb: number,
  handCode: string,
): SimplifiedAction {
  const stacks = [15, 20, 25, 30];
  const closest = stacks.reduce((prev, curr) =>
    Math.abs(curr - stackBb) < Math.abs(prev - stackBb) ? curr : prev
  );

  const key = `${openerPos}_${heroPos}_${closest}`;
  const ranges = COMPILED_RANGES.facingOpen.get(key);
  if (!ranges) return SimplifiedAction.FOLD;

  if (ranges.jam.has(handCode)) return SimplifiedAction.JAM;
  if (ranges.call.has(handCode)) return SimplifiedAction.CALL;
  return SimplifiedAction.FOLD;
}

// Get all hands that have a specific action for a given scenario
export function getHandsForAction(
  position: Position,
  stackBb: number,
  action: SimplifiedAction,
): HandCombo[] {
  return ALL_HANDS.filter(h => getOpeningAction(position, stackBb, h.code) === action);
}
